#!/usr/bin/php       //sayfanın console uygulaması oldugunu söyledik
#!/usr/bin/env php
<?php

if($argv[1]=="-m"){

    $a=$argv[2];

    $class="<?php
namespace Entity;
   
use Core\DataAccess\MySql\Model;
class $a extends Model{
   
   protected  $"."table = 'db_name';
   
}";

    $dt=fopen('Entity/'.$argv[2].'.php','w');
    fwrite($dt,$class);
    fclose($dt);
    echo 'Entity/'.$argv[2].'.php created succesfully';
}